import { json, LoaderFunction } from "@remix-run/node";
import { useLoaderData, useParams } from "@remix-run/react";

export const loader: LoaderFunction = async ({ params }) => {
  const { slug } = params;
  
  console.log("📄 AI Answer Page - Slug:", slug);
  
  // For now, return mock data
  // Later we'll fetch from Sanity or generate fresh with AI
  const mockAnswers = {
    "ai-1759357231581": {
      question: "What's your pricing for interior design?",
      answer: "At Whitefire's company in Anambra, our interior design pricing is transparent and competitive. We offer: Initial consultation (₦25,000), Room design packages (₦150,000-₦500,000), Full home design (₦1,000,000+). Contact us for detailed quote based on your specific needs and space requirements.",
      confidence: 0.95,
      relatedProjects: ["kitchen-renovation", "living-room-makeover"]
    }
  };
  
  // Try to find the answer, fallback to fresh AI generation
  const answer = mockAnswers[slug] || await generateFreshAnswer(slug);
  
  return json({ answer });
};

async function generateFreshAnswer(slug: string) {
  // This would call Gemini API to generate a fresh answer
  // For now, return a fallback
  return {
    question: "Interior Design Question",
    answer: "Whitefire's company in Anambra provides expert interior design services. Contact us for personalized consultation and detailed information about your specific project needs.",
    confidence: 0.8,
    relatedProjects: []
  };
}

export default function AIAnswerPage() {
  const { answer } = useLoaderData();
  
  return (
    <div className="min-h-screen bg-gray-50 pt-24">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
          <div className="mb-6">
            <h1 className="text-3xl font-bold text-gray-900 mb-4">
              {answer.question}
            </h1>
            <div className="flex items-center mb-4">
              <span className="bg-green-100 text-green-800 text-sm px-3 py-1 rounded-full">
                ✅ {Math.round(answer.confidence * 100)}% Confidence - Whitefire's Expertise
              </span>
            </div>
          </div>
          
          <div className="prose prose-lg max-w-none">
            <p className="text-gray-700 leading-relaxed">
              {answer.answer}
            </p>
          </div>
          
          <div className="mt-8 pt-6 border-t border-gray-200">
            <p className="text-sm text-gray-500">
              This answer was generated by Whitefire's AI based on their expertise in interior design in Anambra State.
            </p>
            <div className="mt-4">
              <Link to="/contact" className="text-blue-600 hover:text-blue-800 font-medium">
                Contact Whitefire for personalized advice →
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
